---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/
    repoURL: 'https://github.com/robertzd/argo-k3s-prod'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
